sudo: false
language: generic
env:
  HADOLINT: "${HOME}/hadolint"
  NAME: ghostlink
  REPO: service-ddns-digitalocean
git:
  depth: false
services:
  - docker
install:
  - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.16.0/hadolint-$(uname -s)-$(uname -m)" && chmod 700 ${HADOLINT}
  - apt install git
script:
  - shellcheck DDNS-Timer.sh
  - git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}
after_success:
  - docker push -u "${NAME}" -p "${HUBKEY}"
  - docker build -t "${NAME}""${REPO}":latest .
deploy:
  provider: script
  script: docker push "${NAME}""${REPO}":latest
